# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool: Self-Hosted-1

steps:
  - powershell: |
      $json = Get-Content -Path $(Build.SourcesDirectory)\config.json | ConvertFrom-Json

      $json.enviroment = "staging"

      $json | ConvertTo-Json -Depth 10 | Set-Content -Path $(Build.SourcesDirectory)\config.json
    displayName: "Modify JSON File with PowerShell"


  - powershell: |
      cd public
      mkdir _config
    displayName: "Create Config Folder In Public"

  - task: DownloadSecureFile@1
    displayName: "Download config File"
    inputs:
      secureFile: "config.json"

  - task: DownloadSecureFile@1
    displayName: "Download Data Templates File"
    inputs:
      secureFile: "data_temp.js"


  - task: DownloadSecureFile@1
    displayName: "Download .env File"
    inputs:
      secureFile: ".env"

  - task: CopyFiles@2
    displayName: "Copy .env File Into Project Folder"
    inputs:
      SourceFolder: "$(Agent.TempDirectory)"
      Contents: ".env"
      TargetFolder: "$(Build.SourcesDirectory)"

  - task: CopyFiles@2
    displayName: "Copy Config Files Into Public Folder"
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: |
        config.json
        _dataTemplates.js
      TargetFolder: '$(Build.SourcesDirectory)/public/_config'


  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: "install"
      workingDir: ""
      customRegistry: "useFeed"
      customFeed: "db7a7be3-b4a6-4fc1-b8be-0f85048bfaab"

  - script: |
      npm install -g firebase-tools
      npm install dotenv dotenv-expand
    displayName: "Install Firebase Hosting & DotEnv"

  - task: Npm@1
    displayName: "npm build"
    inputs:
      command: "custom"
      workingDir: ""
      customCommand: "run build"
      customRegistry: "useFeed"
      customFeed: "db7a7be3-b4a6-4fc1-b8be-0f85048bfaab"

  - script: |
      firebase deploy --token $(FIREBASE_TOKEN)
    displayName: "Deploy To Firebase"
